Add a --recursive option duneci-install-module
aburch/dune-docker pull request #8
Opened 2018-04-16 09:50 UTC by dokempf

This is needed for Dune modules that use git submodules
to initialized the submodules and potentially even their
submodules.

Please review carefully, I did not have a setup to test this.

2018-04-16 11:24 UTC, aburch requested changes

2018-04-16 11:24 UTC, aburch commented on base-common/duneci-install-module
> +git_clone_opts=(--depth=1 --no-single-branch "${recursive}")
This looks wrong as it would add either `0` or `1` (as a string).  There is code to add the correct option below, so this should just be dropped.

2018-04-16 11:24 UTC, aburch commented on base-common/duneci-install-module
> +if [[ ${recursive} ]]; then
`0` is true (as a non-empty string):
```
% if [[ 0 ]]; then echo true; fi
true
```

Just use `recursive=` (empty string) earlier and `if [[ -n "${recursive}" ]];` here.

2018-04-16 11:38 UTC, dokempf commented
I adressed your comments in the latest commit. One of them was just my sloppiness, the other one my limited bash knowledge...

2018-04-23 11:08 UTC, dokempf commented
@aburch Could you have another look?

2018-04-24 09:24 UTC, merged

2018-04-24 09:26 UTC, dokempf commented
Thanks! When will the base images include this approximately?

2018-04-24 09:30 UTC, aburch commented
Once this pipeline finishes in a few minutes: https://gitlab.math.tu-dresden.de/ansgar/dune-docker/pipelines/1054
(The CI system builds images for the CI system automatically ;) )